version: "3.3"

services:
  web:
    image: nginx:latest
    restart: always
    environment:
      - TZ="Asia/Taipei"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app      
    networks:
      - st-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
  phpMyAdmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - "PMA_HOSt=${DB_HOST}"
    ports:
      - "9080:80"
    depends_on: 
      - db
    networks:
      - st-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"         
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    restart: always
    volumes:
      - ./:/var/www
    depends_on: 
      - db   
    environment:
      - "DB_PORT=${DB_PORT}"
      - "DB_HOST=${DB_HOST}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"      
      - TZ="Asia/Taipei"
    networks:
      - st-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
  radius:
    build:
      context: ./
      dockerfile: radius.dockerfile
    restart: always
    environment:
      - TZ="Asia/Taipei"    
    ports:
      - "1812-1813:1812-1813/tcp"
      - "1812-1813:1812-1813/udp"
    networks:
      - st-network
    depends_on: 
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
  db:
    image: mariadb:10
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
#    command: --init-file /radiuscdr.sql
    volumes:
      - "mariadb-data:/var/lib/mysql"
#      - ./radiuscdr.sql:/radiuscdr.sql
    networks:
      - st-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
  phpMyAdmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - "PMA_HOSt=${DB_HOST}"
    ports:
      - "9080:80"
    depends_on: 
      - db
    networks:
      - st-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5" 
volumes:
  mariadb-data:
networks:
  st-network: